### ISSUE TITLE
Failed build win7/64

### ISSUE THREAD

**Issue by xcrimson** [bsl/GLFW-b#52] opened 2015-04-18 07:46 UTC
>Loading package ghc-prim ... linking ... done.
>Loading package integer-gmp ... linking ... done.
>Loading package base ... linking ... done.
>Loading package bindings-DSL-1.0.22 ... linking ... done.
>Loading package bindings-GLFW-3.1.1.2 ... linking ... ghc.exe: unable to load package `bindings-GLFW-3.1.1.2'
>ghc.exe: warning: _vsnprintf from msvcrt is linked instead of __imp__vsnprintf
>ghc.exe: C:\Users\crimson\AppData\Roaming\cabal\x86_64-windows-ghc-7.8.3\bindings-GLFW-3.1.1.2\HSbindings-GLFW-3.1.1.2.o: unknown symbol `strdup'
>cabal: Error: some packages failed to install:
>GLFW-b-1.4.7.2 failed during the building phase. The exception was:
>ExitFailure 1

Win7/64

**Comment by schell** [comment] 2015-04-18 18:00
Yes - this seems to be a duplicate of https://github.com/bsl/bindings-GLFW/issues/27. I'm installing windows/mingw/minghc on a vm to try to fix this :)

I'll close this one out and @xcrimson you can follow along at the bindings-GLFW repo.

**Closed by schell** 2015-04-18 18:00 UTC
