### ISSUE TITLE
glfwPostEmptyEvent added in GLFW 3.1 would be really handy

### ISSUE THREAD

**Issue by evanrinehart** [bsl/GLFW-b#46] opened 2015-02-19 11:28 UTC
Shouldn't be hard to add to the bindings. This command would be useful to let a thread wake up the main thread which is blocked indefinitely waiting for events. Polling reduces responsiveness and wastes CPU.

**Comment by evanrinehart** [comment] 2015-02-19 11:37
I see that 3.1 support is currently in the works.

**Comment by schell** [comment] 2015-02-19 17:47
Yes :) I'll close this as it's a duplicate of https://github.com/bsl/bindings-GLFW/pull/18.

**Closed** 2015-02-19 17:47 UTC
